### PR TITLE
Pass ID via object when hydrating response.author, including embedded author object if available

### PR DESCRIPTION
**Pull request by westonruter**
Fixes issue where a Backbone model needs an attributes object to be passed into `wp.api.models.User()`, not a bare ID, when hydrating `response.author` in `TimeStampedMixin.parse()`.

Additionally, if the request includes `_embed`, then the embedded author object is supplied instead of just `{ id: response.author }`.

### CODE REVIEW

**Comment by westonruter** [comment]
It seems that in the refactored code, however, that `TimeStampedMixin` is not even being used currently in the Backbone models. Additionally, `TimeStampedMixin` is missing a `var` declaration, or getting attached to a `wp.api` namespace.

**Comment by adamsilverstein** [comment]
Thanks for bringing that to my attention, will work on adding it back to the models where appropriate.

**Comment by westonruter** [comment]
For that matter, I don't see any of the Backbone models (`User`, `Post`, etc) at all :smile:

**Comment by adamsilverstein** [comment]
:) are you running the plugin? i'm not sure this user mixin makes sense, what happens if you go to save the model?

**Comment by westonruter** [comment]
Closing in favor of PR to `master`: https://github.com/WP-API/client-js/pull/66

**Pull request closed without merging**
